### ISSUE TITLE
manifest parsing error with serde_xml_rs

### ISSUE THREAD

**Issue by Linus2hell** [UbiqueInnovation/coeus-rs#7]
Hi there,

i found an error while extracting the manifest file with the `get_manifests()` method in the _parse.rs_ file. It seems to be related to the used **serde_xml_rs** version.

Observation:

- running:`ao.get_manifests()[0].get_xml()` is doing well but `ao.get_manifests()[0].get_json()` is returning `'{"versionCode":"","versionName":"","package":"","$value":[]}'`. 
Tried this for several apks.
Reason for this is the `serde_xml_rs::from_str(&content)` line (194) in _extraction.rs_ which throws an Error: **UnexpectedToken { token: "&XmlEvent::Characters(ref name) |\n&XmlEvent::StartElement { name: OwnedName { local_name: ref name, .. }, .. }", found: "EndElement(activity)" }** and sets the AndroidManifest::default().

- updated to **serde_xml_rs** version **0.6.0** but got the same error

- downgrade to **serde_xml_rs** version **0.4.1** works like a charm 

Hope this is useful to improve this great tool!

Best regards

**Comment by ubamrein** [comment]
Thanks for this hint! Since transcoding XML to JSON was not as good an idea as I imagined in the beginning, I'd rather use the binary-decoded XML directly. To analyse the XML structure, I'd suggest to use pythons builtin xml parser. For example to extract the `minSdk` value:

```python
from xml.dom.minidom import parseString
[...]

xml = parseString(ao.get_manifests()[0].get_xml())
usesSdk = xml.getElementsByTagName("uses-sdk")[0]
if usesSdk.hasAttribute("android:minSdkVersion"):
    minSdkVersion = int(usesSdk.attributes["android:minSdkVersion"].value)
```

But the downgrade will be merged with https://github.com/UbiqueInnovation/coeus-rs/pull/8 resp. https://github.com/UbiqueInnovation/coeus-rs/pull/6, and so the issue should be "fixed" for now.
